version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/usr/src/app
      - ./backend/data:/data

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: rq worker --url redis://redis:6379/0
    depends_on:
      - web
      - redis
    volumes:
      - ./backend:/usr/src/app
